awbGain:
- 1.5
- 1.5
awbMode: 'off'
brightness: 50
colorEffects: null
contrast: 0
crop:
- 0.0
- 0.0
- 1.0
- 1.0
exposureCompensation: 0
exposureMode: false
hflip: []
imageEffects: none
iso: 100
meterMode: average
previewLength: 3
resolution:
- 2592
- 1944
rotation: 0
saturation: 0
sharpness: 0
shutterSpeed: 750000
vflip: false
videoStabilization: false
